Feature/add riddle logic and interface to map
Alvaro2112/Money_run pull request #147
Opened 2021-04-07 09:00 UTC by Alvaro2112

2021-04-07 10:12 UTC, gauthierboeshertz approved these changes

2021-04-07 10:14 UTC, gauthierboeshertz requested changes
Please change the name of the riddle database variable.

2021-04-07 14:11 UTC, gauthierboeshertz approved these changes

2021-04-08 17:09 UTC, gauthierboeshertz approved these changes

2021-04-08 17:14 UTC, Warhedgehog approved these changes

2021-04-08 19:07 UTC, merged