Diminish Database pollution with testing values
Alvaro2112/Money_run pull request #276
Opened 2021-05-12 17:11 UTC by Warhedgehog

2021-05-13 19:35 UTC, RafaelRamirezS approved these changes
Good code cleanup, nothing to add

2021-05-21 16:30 UTC, Alvaro2112 requested changes
You should try to fix the CC issues

2021-05-21 17:39 UTC, Alvaro2112 requested changes

2021-05-21 17:39 UTC, Alvaro2112 commented on app/src/main/java/sdp/moneyrun/database/GameDatabaseProxy.java
> +            throw new IllegalArgumentException("game should not be null.");
These checks should be tested

2021-05-21 17:39 UTC, Alvaro2112 commented on app/src/main/java/sdp/moneyrun/database/UserDatabaseProxy.java
> +        if(user == null){
Same here

2021-05-21 17:39 UTC, Alvaro2112 commented on app/src/main/java/sdp/moneyrun/game/Game.java
> +        if (players == null) {
Same here as well

2021-05-21 18:08 UTC, Warhedgehog commented on app/src/main/java/sdp/moneyrun/game/Game.java
> +        if (players == null) {
Same here

2021-05-21 18:08 UTC, Warhedgehog commented on app/src/main/java/sdp/moneyrun/database/UserDatabaseProxy.java
> +        if(user == null){
I didn't write this, I'm pretty sure

2021-05-21 18:08 UTC, Warhedgehog commented on app/src/main/java/sdp/moneyrun/database/GameDatabaseProxy.java
> +            throw new IllegalArgumentException("game should not be null.");
Agreed

2021-05-21 18:09 UTC, Warhedgehog commented
> You should try to fix the CC issues

The first two is about code I did not write. The last two should be discarded IMO

2021-05-21 20:53 UTC, Alvaro2112 approved these changes

2021-05-21 21:26 UTC, merged