Feature/shrinking radius
Alvaro2112/Money_run pull request #280
Opened 2021-05-13 13:39 UTC by Tesa27

This is a first draft implementation of a radius that should shrink over time as time advances, for now it is not compatible with the coin interface but that is an upcoming challenge.

2021-05-13 14:12 UTC, gauthierboeshertz requested changes

2021-05-13 14:12 UTC, gauthierboeshertz commented on app/src/androidTest/java/sdp/moneyrun/map/MapInstrumentedTest.java
> +    public void checkIfShrinkCircleDrawsSmallerCircleWithCorrectShrinkPace(){
This doesnt really test anything

2021-05-13 14:13 UTC, gauthierboeshertz requested changes

2021-05-13 14:13 UTC, gauthierboeshertz commented on app/src/main/java/sdp/moneyrun/ui/map/MapActivity.java
> +        while(currentTimeMillis() - initTime < paceInMillis){}
Blocking the activity thread for some time looks like a bad practice

2021-05-14 14:25 UTC, gauthierboeshertz approved these changes

2021-05-14 15:33 UTC, Alvaro2112 requested changes
I think you should add Javadoc to the functions you coded, also, have you use the reformatter and the code analysis tool to fix any warnings?

2021-05-14 15:33 UTC, Alvaro2112 commented on app/src/main/java/sdp/moneyrun/menu/JoinGameImplementation.java
> +//                    if (distance > MAX_DISTANCE_TO_JOIN_GAME) {
Comments should be removed

2021-05-14 15:33 UTC, Alvaro2112 commented on app/src/main/java/sdp/moneyrun/ui/map/MapActivity.java
> +        //circleOptions.withCircleColor(ColorUtils.colorToRgbaString(getResources().getColor(R.color.colorPrimary)));
Same here

2021-05-14 16:39 UTC, Tesa27 commented on app/src/main/java/sdp/moneyrun/ui/map/MapActivity.java
> +        //circleOptions.withCircleColor(ColorUtils.colorToRgbaString(getResources().getColor(R.color.colorPrimary)));
done

2021-05-14 16:40 UTC, Tesa27 commented on app/src/main/java/sdp/moneyrun/menu/JoinGameImplementation.java
> +//                    if (distance > MAX_DISTANCE_TO_JOIN_GAME) {
done

2021-05-16 09:14 UTC, Alvaro2112 approved these changes

2021-05-16 10:10 UTC, merged