change background
Alvaro2112/Money_run pull request #372
Opened 2021-05-29 14:56 UTC by gauthierboeshertz

2021-05-29 22:05 UTC, Alvaro2112 requested changes

2021-05-29 22:05 UTC, Alvaro2112 commented on app/src/main/java/sdp/moneyrun/ui/map/MapActivity.java
> +        Coin coin = nearestCoin(location, localPlayer.getLocallyAvailableCoins(), 5*THRESHOLD_DISTANCE);
You forgot to change this back

2021-05-30 10:15 UTC, Alvaro2112 approved these changes

2021-05-30 16:14 UTC, RafaelRamirezS approved these changes
no major logic changes, good improvements and generalizing of the theme to the entire app

2021-05-30 16:14 UTC, merged