First draft of code wit tests passing
Alvaro2112/Money_run pull request #88
Opened 2021-03-19 17:29 UTC by Warhedgehog

For an unknown reason, I there seems to be a bug with the checks on github. The tests passes and the functionality has been "manually" tested with firebase on top of that

2021-03-23 18:34 UTC, Tesa27 approved these changes

2021-03-24 09:48 UTC, Alvaro2112 submitted a review, later dismissed

2021-03-24 13:21 UTC, Alvaro2112 requested changes
I think we should try to stick with the code climate rules, It shouldn't be too hard to make the duplicate code into a single function that you can then reuse.

2021-03-24 14:20 UTC, Alvaro2112 approved these changes

2021-03-24 19:07 UTC, merged